/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const appConfig: typeof import('../src/shared/helpers/const')['appConfig']
  const baseSeo: (typeof import("../../../shared/helpers/seo"))["baseSeo"]
  const clientEnvs: typeof import('../src/shared/helpers/client-envs')['clientEnvs']
  const configSWRHeaders: typeof import('../src/shared/helpers/cache')['configSWRHeaders']
  const copyTextToClipboard: typeof import('../src/shared/helpers/event')['copyTextToClipboard']
  const createRef: typeof import('react')['createRef']
  const formatDateTimeRelative: typeof import('../src/shared/helpers/date')['formatDateTimeRelative']
  const forwardRef: typeof import('react')['forwardRef']
  const getAgentParser: typeof import('../src/shared/helpers/client')['getAgentParser']
  const getFulfilledValue: typeof import('../src/shared/helpers/promises')['getFulfilledValue']
  const getLanguage: typeof import('../src/shared/helpers/geometry')['getLanguage']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const request: typeof import('../src/shared/helpers/request')['default']
  const seoLinkHead: (typeof import("../../../shared/helpers/seo"))["seoLinkHead"]
  const seoMetaHead: (typeof import("../../../shared/helpers/seo"))["seoMetaHead"]
  const startTransition: typeof import('react')['startTransition']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
}
