#!/bin/bash -e

# regex to validate in commit msg
ticketReg='^(STL-[A-Z0-9]{2,4}|merge|hotfix|release)'
errorMsg="Aborting commit. Your commit message must start with JIRA/Plane code (eg: 'STL-1111') or 'merge|hotfix|release'"

if ! grep -iqE "$ticketReg" "$1"; then
    echo "$errorMsg" >&2
    exit 1
fi
