#!/bin/bash -e

# regex to validate in commit msg
commit_regex='^(TML-[A-Z0-9]{2,4}|merge|hotfix|release)'
error_msg="Aborting commit. Your commit message must start with JIRA code (eg: 'TML-1111') or 'merge|hotfix|release'"

if ! grep -iqE "$commit_regex" "$1"; then
    echo "$error_msg" >&2
    exit 1
fi